# Generated by Django 4.0.4 on 2022-04-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_categoria_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
